@startuml
actor Reclutador
actor Candidato

rectangle "Seguimiento y Evaluación de Candidatos" {
    usecase "Programar Entrevista" as U1
    usecase "Registrar Evaluación del Candidato" as U2
    usecase "Actualizar Estado del Proceso" as U3
    usecase "Enviar Notificación al Candidato" as U4
}

Reclutador --> U1
Reclutador --> U2
Reclutador --> U3
U3 --> U4
Candidato <-- U4
@enduml

